const aulasReactAvancado = [
  ["Usando states em um class component"],
  ["Importância da arrow function no React"],
  ["Componente Stateless vs Componente Statefull"],
  ["Lifecycle ou ciclos de vida no React"],
  ["Ciclos de vida na prática"],
  ["Introdução aos Hooks"],
  ["Hook de estado - useState"],
  ["Hook de efeito - useEffect"],
  ["Renderização condicional"],
  ["Formulários"],
  ["A melhor forma de Criar Formulários no ReactJS com React Hook Form"],
  ["Trabalhando com vários inputs"],
  ["Rotas no React"],
  ["Criando página interna e navegação"],
  ["Estilizando Componentes com styled components"],
  ["Global Styles com createGlobalStyle"],
  ["Como utilizar o React Query na prática"],
  ["Consumindo API no front-end com AXIOS"],
  ["Consumindo API no front-end com AXIOS - Parte 2"],
];
